version: '3'
services:
  github-user-service:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - .:/home/node/app
    ports:
      - "3000:3000"
    command: /bin/sh -c "npm install && npm run build && npm start"
